// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bank.Models;

namespace alpro.Migrations
{
    [DbContext(typeof(dbbank))]
    partial class dbbankModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bank.Models.fasilitas", b =>
                {
                    b.Property<string>("jns_fasilitas")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("nama_fasilitas")
                        .HasColumnType("varchar(200)");

                    b.HasKey("jns_fasilitas");

                    b.ToTable("fasilitas");
                });

            modelBuilder.Entity("bank.Models.nasabah", b =>
                {
                    b.Property<string>("ciff_nasabah")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("alamat_nasabah")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("jk_nasabah")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("nama_nasabah")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("nohp_nasabah")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("pekerjaan_nasabah")
                        .HasColumnType("varchar(200)");

                    b.HasKey("ciff_nasabah");

                    b.ToTable("nasabah");
                });

            modelBuilder.Entity("bank.Models.transaksi", b =>
                {
                    b.Property<string>("ciff_nasabah")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("jns_fasilitas")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("keterangan_transaksi")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("nominal_transaksi")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("tgl_transaksi")
                        .HasColumnType("date");

                    b.HasKey("ciff_nasabah");

                    b.ToTable("transaksi");
                });

            modelBuilder.Entity("bank.Models.fasilitas", b =>
                {
                    b.HasOne("bank.Models.transaksi", null)
                        .WithMany("fasilitas")
                        .HasForeignKey("jns_fasilitas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bank.Models.transaksi", b =>
                {
                    b.HasOne("bank.Models.nasabah", null)
                        .WithMany("transaksi")
                        .HasForeignKey("ciff_nasabah")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bank.Models.nasabah", b =>
                {
                    b.Navigation("transaksi");
                });

            modelBuilder.Entity("bank.Models.transaksi", b =>
                {
                    b.Navigation("fasilitas");
                });
#pragma warning restore 612, 618
        }
    }
}
